version: '3.8'

services:
  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - chifles-network
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ./api
    environment:
      DB_HOST: database
      DB_USER: chifles_user
      DB_PASSWORD: chifles_password
      DB_NAME: chifles_db
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - chifles-network

networks:
  chifles-network:
    driver: bridge

volumes:
  mysql_data: