FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=chifles_db
ENV MYSQL_USER=chifles_user
ENV MYSQL_PASSWORD=chifles_password

COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306